services:
  django:
    build:
      context: . # Dockerfileがあるディレクトリまでの相対パス
      dockerfile: Dockerfile # Dockerfileのファイル名
    ports:
      - "8000:8000"
    tty: true
    volumes:
      # ローカルの作業ディレクトリと仮想環境の作業ディレクトリの対応づけ
      - ${SRC_PATH}:/root/workspace
